# File: deployment/kubernetes/secrets.yaml
# Kubernetes secrets for sensitive data

apiVersion: v1
kind: Secret
metadata:
  name: fe-ai-secrets
  namespace: fe-ai
type: Opaque
data:
  # Base64 encoded values (replace with actual encoded secrets)
  mongo-username: ZmVhaV91c2Vy  # feai_user
  mongo-password: c2VjdXJlX3Bhc3N3b3JkXzEyMw==  # secure_password_123
  redis-password: cmVkaXNfcGFzc3dvcmRfMTIz  # redis_password_123
  secret-key: eW91cl9zZWNyZXRfa2V5X2hlcmU=  # your_secret_key_here
  jwt-secret: and0X3NlY3JldF9rZXlfaGVyZQ==  # jwt_secret_key_here
  encryption-key: ZW5jcnlwdGlvbl9rZXlfaGVyZQ==  # encryption_key_here